[project]
name = "jsonschema-to-zon"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "zon>=2.0.1",
]

[dependency-groups]
dev = [
    "black>=24.10.0",
    "pylint>=3.3.3",
    "pytest>=8.3.4",
]
