name: CI

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        version: [3.13]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.version}}
      uses: actions/setup-python@v3
      with:
        python-version: "${{ matrix.version }}"
    
    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Install dependencies
      run: |
        uv sync

    - name: Run Pylint
      run: pylint jsonschema-to-zon

  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        version: [3.13]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.version}}
      uses: actions/setup-python@v3
      with:
        python-version: "${{ matrix.version }}"
    
    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Install dependencies
      run: |
        uv sync
      
    - name: Run tests
      run: pytest tests
  
    - name: Upload coverage to Coveralls
      uses: coverallsapp/github-action@v2